### ISSUE TITLE
'Handle bins' functionality

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#115]
This issue is to report that the 'handle bins' functionality is returning an 'internal server error' for the text/tabular option.

![image](https://user-images.githubusercontent.com/26254388/119144450-ab3ed280-ba16-11eb-87f8-152c3fd45eaf.png)

**Comment by hyi** [comment]
@karafecho This issue has been fixed and can be closed I believe.

**Comment by karafecho** [comment]
Yes, we can close this issue.
