### ISSUE TITLE
Incorrect MaxDailyPM2.5Exposure_StudyMax feature bin levels through Port 16340

### ISSUE THREAD

**Issue by Sharma05** [NCATS-Tangerine/icees-api#121]
Identified binning issues with MaxDailyPM2.5Exposure_StudyMax feature during the comparison of underlying ICEES table and multivariate tables generated from the API (port 16340). The underlying table revealed that MaxDailyPM2.5Exposure_StudyMax feature has only 2 levels or bins i.e MaxDailyPM2.5Exposure_StudyMax_1 and MaxDailyPM2.5Exposure_StudyMax_5 where as the data after API generated  bin levels from MaxDailyPM2.5Exposure_StudyMax_1, MaxDailyPM2.5Exposure_StudyMax_2, MaxDailyPM2.5Exposure_StudyMax_3, MaxDailyPM2.5Exposure_StudyMax_4, MaxDailyPM2.5Exposure_StudyMax_5. The previous version of the data (Version 3) on port 16399, revealed that MaxDailyPM2.5Exposure_StudyMax has five levels. 

@Hao, further looked into the pipeline and identify that the pipeline didn't generate the MaxDailyPM2.5Exposure_StudyMax correctly in the current version (Version 4) of the data. The pipeline is be rerun.

**Comment by patrickkwang** [comment]
This issue is upstream of the API.
