### ISSUE TITLE
Terms & Conditions - ICEES+ COVID-19 instance

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#136]
This issue is to report an incorrect statement in the terms & conditions that are returned to users of the ICEES+ COVID-19 instance. the correct statement is:

*"Attribution should include acknowledgement of the funder, the National Center for Advancing Translational Sciences (awards OT3TR002020, 1OT2TR003430, UL1TR002489, 3UL1TR002489-03S4). "*

**Comment by patrickkwang** [comment]
Superceded by #175
