### ISSUE TITLE
Odd results

### ISSUE THREAD

**Issue by cbizon** [NCATS-Tangerine/icees-api#153]
This is in on the DILI iccees, the query is 

```
{"message":{"query_graph":{
  "edges": {
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0005359"
      ],
      "is_set": False,
      "name": "drug-induced liver injury"
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "is_set": False,
      "name": "Disease Or Phenotypic Feature"
    }
  }
}
}}
```

i.e. phenotypic features correlated with DILI.

There are things coming back that I'm not sure are phenotypic features?  e.g. sex, racePCA and ethnicity.  

Also, sex has a bogus coding:
MESH:C110500.  The node normalizer claims that this is a chemical substance, and the description from mesh says:
"a commercially-available herbomineral formulation; contains Prativisha (Aconitum palmatum), Cowrie bhasma, Shankh bhasma, Maricha (Piper nigrum), Vidanga (Embelia ribes), Triphala & Sunthi (Zingiber officinale); do not confuse with Gas-X"

The identifier for race is also wrong, and the one for ethnicity claims to be 'retired'.

**Comment by patrickkwang** [comment]
Moved to https://github.com/NCATS-Tangerine/icees-api-config/issues/30
