### ISSUE TITLE
root_path

### ISSUE THREAD

**Issue by xu-hao** [NCATS-Tangerine/icees-api#163]
root_path cause the document not display https://covid.icees.renci.org/jan2021/apidocs

**Comment by karafecho** [comment]
Also see [this issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/213) and note that Colleen suggests that we removed older SmartAPI registrations, but I don't think we want to do that, as each deployment of the ICEES+ COVID API exposes data on a different cohort.
