### ISSUE TITLE
EPR YAML Configuration File

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#17]
AFTER the prototype demo, perhaps we can make the following changes to the EPR data in the YAML config file:

The following feature variables should be mapped to 'gene' and 'phenotypic feature' or just 'gene'.
SNP1:
    type: string
    enum: ['A', 'C', 'B']
    biolinkType: PhenotypicFeature
  SNP2:
    type: string
    enum: ['Z', 'X', 'Y']
    biolinkType: PhenotypicFeature
  SNP3:
    type: string
    enum: ['E', 'F', 'D']
    biolinkType: PhenotypicFeature
  SNP4:
    type: string
    enum: ['N', 'L', 'M']
    biolinkType: PhenotypicFeature

The following feature variables should be mapped to 'chemical substance':
O3_ANNUAL_AVERAGE_cut:
    type: integer
    minimum: 1
    maximum: 5
    biolinkType: Environment
  O3_ANNUAL_AVERAGE_qcut:
    type: integer
    minimum: 1
    maximum: 5
    biolinkType: Environment
  O3_N_OBS:
    type: integer
    biolinkType: Environment
  PM25_ANNUAL_AVERAGE_cut:
    type: integer
    minimum: 1
    maximum: 5
    biolinkType: Environment
  PM25_ANNUAL_AVERAGE_qcut:
    type: integer
    minimum: 1
    maximum: 5
    biolinkType: Environment
  PM25_N_OBS:
    type: integer
    biolinkType: Environment

**Comment by patrickkwang** [comment]
Upstream (config) issue.
