### ISSUE TITLE
Bug in "bins" endpoint

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#177]
This issue is to report a bug in the "bins" endpoint for all ICEES+ instances. Specifically, the text/tabular output option does not work, but the json output option does. The bug appears to be in the formatter.

**Comment by hyi** [comment]
@karafecho I fixed a big for the "bins" endpoint a while back and the endpoint is working for me. Can you check it again to see if this issue is resolved?

**Comment by karafecho** [comment]
Works fine for me! Thanks, Hong.
