### ISSUE TITLE
Update automated tests for KG endpoint

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#185]
This issue is to request that the [automated tests for the KG endpoint](https://github.com/NCATS-Tangerine/icees-api/blob/master/test/api/test_knowledge_graph.py) are updated to TRAPI 1.2.0.

**Comment by davefol** [comment]
Addressed by: https://github.com/davefol/api-watchdog-translator-tests/commit/5c5fe8cb94c1cfc4e92df8f0c015cf788d5d6982
