### ISSUE TITLE
ICEES DILI production instance - Workflow B.1 one-hop spins

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#206]
This issue is to report that the ICEES DILI production instance does not return results for the initial one-hop in the Workflow B.1 query. This may or may not be related to caching.

**Comment by karafecho** [comment]
![image](https://user-images.githubusercontent.com/26254388/143076686-59fc1d0f-ee50-4acd-9d6b-56e18f79def9.png)

**Comment by maximusunc** [comment]
Hi Kara, could you post the query raw json so we can reproduce this issue please?

**Comment by karafecho** [comment]
Sure thing. I tested the below query with one and with both input CURIES.

{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicates": [
            "biolink:has_real_world_evidence_of_association_with"
          ]
        }
      },
      "nodes": {
        "n00": {
          "ids": ["MONDO:0005359", "SNOMEDCT:197354009"],
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ]
        },
        "n01": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ]
        }
      }
    },
    "knowledge_graph": {
      "nodes": {},
      "edges": {}
    },
    "results": []
  }
}

**Comment by karafecho** [comment]
Note that Kenny was able to run a one-hop via direct CURL. In my experience, if Swagger fails, then CURL fails, and vice versa, but that appears to be an incorrect assertion. Alternatively, the issue may be related to connectivity issues on my end.

**Comment by kennethmorton** [comment]
Oh no, I ran things through Swagger.

**Comment by karafecho** [comment]
Oh, thanks for the clarification. In that case, I think we can close this issue.
