### ISSUE TITLE
Provide ReasonerStd overlay/support API

### ISSUE THREAD

**Issue by cbizon** [NCATS-Tangerine/icees-api#21]
We would like to use ICEES as a support edge generator using co-occurrences.  The interface would be the Reasoner API.  The input query graph would not be required, but there would be an input knowledge_graph, and often a list of results.

A cohort could be defined in options to the query, but will default to the universal cohort.

The service will then return a knowledge graph that is the old knowledge graph, plus new edges that represent co-occurrence between the concepts.  A simple version could add such an edge between every pair of nodes in the graph; a more refined approach would only connect nodes that appear in a result together.  Some of this logic may be appropriated from the robokop messenger support endpoint (paging @patrickkwang ).   

I could also imagine options for things like significance cutoffs.

**Comment by karafecho** [comment]
@xu-hao will address this on or  before June 12.

**Comment by xu-hao** [comment]
Multiple exposure feature variables can be mapped to the same curie. e.g. max avg. What should we do in this case?

**Comment by patrickkwang** [comment]
So we're talking about e.g. MaxDailyOzoneExposure vs. AvgDailyOzoneExposure and want to ask "How strongly does ozone co-occur with X?"

We could just try to choose which of those ozone features is best to answer that question.

Or we could ask that question of all ozone features and take the maximum over the results? Or the average? 😁

**Comment by karafecho** [comment]
The problem with option (1) is that the choice really depends on the question. There's also an issue of binning strategies, as we're still trying to determine if there's a single 'best' approach, which there doesn't appear to be.

I'm not sure I understand option (2).

FWIW, I'm inclined to map similar feature variables to the same curie. 

BTW, [this spreadsheet](https://github.com/NCATS-Tangerine/icees-api/blob/master/docs/ICEES_Identifiers_v8%2001.28.20.xlsx), which does not yet include the EPR data, might be helpful.

Just so everyone is aware, I'm working with Anne Thessen and others to figure out how to 'ontologize' the EPR survey data. The work keeps getting de-prioritized, however.

**Comment by cbizon** [comment]
I think I would do something like: 
1. Have a mapping of Ozone as a concept/curie to all relevant icees columns.
2. When you're trying to lok for edges between ozone and X, use all columns mapped in 1.
3. Return all significant edges, with a property saying which icees column was used to calculate that edge.

**Comment by cbizon** [comment]
If we do something like I suggest, we should probably also bonferroni adjust the p

**Comment by karafecho** [comment]
The suggestion above makes sense to me. In (3), I suggest returning the variable name. I don't think we need to worry about Bonferroni corrections as the intent is different here and there really aren't that many mappings per curie. Plus, we've already stacked the odds against finding any significant associations by virtue of design, with exposure estimates based on relatively large grid sizes, coarse binning, one-year 'study periods', etc.

BTW, a side benefit to this approach is that it will allow us to more systematically evaluate binning strategies.

**Comment by cbizon** [comment]
If you don't want to bonferroni adjust, can you return the number of features that were checked?  Then the caller can decide what it needs to do.

**Comment by karafecho** [comment]
It's not that I don't "want" to perform a Bonferroni correction, but rather, I don't see the point.

I think that you, me, Hao, Patrick, and Steve should find a time to discuss this issue and #20 because I'm not sure we're all on the same page, in terms of general goals and the meaning/interpretation of any data/information/knowledge that is returned from calls to the ICEES+ KP. Plus, we're approaching this exercise from different perspectives, you from an -omics perspective, me from a more general clinical research/informatics perspective. I also have a few questions regarding the responsibilities of KPs vs ARAs, and I realize you may not have clear answers, but a discussion might be helpful. Just my two cents...

@cbizon @xu-hao @patrickkwang wang @stevencox : Any chance you are free at 2 pm ET tomorrow, Monday, June 15? If not, perhaps we can find another time?

**Comment by cbizon** [comment]
The point is that if you will performing multiple tests, then it's appropriate to return information related to how many, so that the caller can correctly interpret the results.

I'm free pretty much all day except 2-3:30.

**Comment by karafecho** [comment]
We need to discuss this, as we're not at all on the same page as to what statistics are being performed, why, and how the results should be interpreted.

For instance, if you performed a Bonferonni correction on COHD's dataset, which is pre-calculated, unlike ICEES+, you would end up with something like alpha=0.05/1,000,000 or even smaller.

Also, the 'multiple tests' that you are referring to with ICEES+, in this case, aren't really multiple tests, but rather, different estimates of the exact same variable. Much like the US Census Bureau reports for their ACS estimates.

I am free to meet after 3:30 pm. Others?

**Comment by xu-hao** [comment]
I'm availabe after 2pm.

**Comment by xu-hao** [comment]
another question:

how do we handle icees feature values. in feature association api, we need to specify not only features but also values to generate the contingency matrix. for example pm2.5 are binned into quintiles. We need to specify which value is the cut off point for high and low. We can alternatively use all possible values of a feature, one per row in the contingency matrix, and this will work for pm2.5. but for ed visits, we don't have a fixed number of values. we can treat it as a special case by grouping >=10 together.

**Comment by karafecho** [comment]
These are really important points. In addition to specifying values for each level, we need to specify the function (i.e., qcut vs cut). Note that the values will differ by year, which adds another layer of complexity. WRT ED visits, I think this is one example, but I can imagine others. For instance, we may want to examine the number of times a specification medication was administered over a given time interval.
