### ISSUE TITLE
Trouble running queries on v2.0.0

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#22]
This query works from the command line but not from the Swagger interface ({}, 2.0.0, patient, 2016):  

curl -X POST "https://icees.renci.org:16339/patient/2016/cohort" -H "accept: application/json" -H "Content-Type: application/json" -d "{}"

Same thing with this query (for COHORT:19):

curl -X GET "https://icees.renci.org:16339/patient/2016/cohort/COHORT%3A19/features" -H "accept: text/tabular”

This query simply does not run for me:

curl -X POST "https://icees.renci.org:16339/patient/2016/cohort" -H "accept: text/tabular" -H "Content-Type: application/json" -d "{"TotalEDInpatientVisits":{"operator":"=","value":0}}"

400 Error

Neither does this one:

curl -k -XPOST https://icees.renci.org:16339/patient/2016/cohort/COHORT:19/feature_association -H "Content-Type: application/json" -d “{"feature_a":{"Race":{"operator":"=", "value":”African American”}},"feature_b":{"AvgDailyPM2.5Exposure_StudyAvg_qcut":{"operator":"<", "value":3}}}”
'The system cannot find the file specified.' (edited) 

I think there's an issue with v2.0.0 tables? Possibly also some syntax errors? 

I shouldn't be able to create a cohort from 2016 (new tables), if they aren't loaded into v2.0.0, right?

Also, in my CURLS, I probably should need to specify the version, correct?

Sorry, but I'm a bit confused, and if I'm confused, then others will be, too.

I suspect that the confusion relates to our rush to put out a prototype, but we probably should address these issues sooner rather than later.

**Comment by xu-hao** [comment]
Currently there are two instances of icees running. One is on port 80, which has version 1.0.0 and 2.0.0. The other is on port 16339, which has version 3.0.0.

The plan is that we will consolidate all of them into one port so that it will be less confusing.

There are the two queries that works:

```
curl -k -XPOST https://icees.renci.org:16339/patient/2016/cohort/COHORT:19/feature_association-H "Content-Type: application/json" -d '{"feature_a":{"Race":{"operator":"=","value":"AfricanAmerican"}},"feature_b":{"AvgDailyPM2.5Exposure_StudyAvg_qcut":{"operator":"<", "value":3}}}'

curl -k -XPOST "https://icees.renci.org:16339/patient/2016/cohort" -H "Content-Type: application/json" -d '{"TotalEDInpatientVisits":{"operator":"=","value":0}}'
```

**Comment by karafecho** [comment]
Great! Thanks, @xu-hao!

**Comment by karafecho** [comment]
Actually, @xu-hao, I had already tried the two queries above. Both failed when I first tried them and failed again when I copied and pasted from above. Thoughts?

**Comment by xu-hao** [comment]
Sorry some space got deleted when it was formatted:
```
curl -k -XPOST https://icees.renci.org:16339/patient/2016/cohort/COHORT:19/feature_association -H "Content-Type: application/json" -d '{"feature_a":{"Race":{"operator":"=","value":"African American"}},"feature_b":{"AvgDailyPM2.5Exposure_StudyAvg_qcut":{"operator":"<", "value":3}}}'
```

**Comment by karafecho** [comment]
Well, I'm now getting a 400 error for the bivariate query above and the cohort creation query noted previously.

**Comment by xu-hao** [comment]
On Windows, try to use double quotes instead of single quotes:
```
curl -k -XPOST https://icees.renci.org:16339/patient/2016/cohort/COHORT:19/feature_association -H "Content-Type: application/json" -d "{\"feature_a\":{\"Race\":{\"operator\":\"=\",\"value\":\"African American\"}},\"feature_b\":{\"AvgDailyPM2.5Exposure_StudyAvg_qcut\":{\"operator\":\"<\", \"value\":3}}}"
```

**Comment by xu-hao** [comment]
```
curl -k -XPOST "https://icees.renci.org:16339/patient/2016/cohort" -H "Content-Type: application/json" -d "{\"TotalEDInpatientVisits\":{\"operator\":\"=\",\"value\":0}}"
```

**Comment by xu-hao** [comment]
First query:
On Windows, try to use double quotes instead of single quotes and escape the double quotes inside the outermost quotes.
```
curl -k -XPOST "https://icees.renci.org:16339/patient/2016/cohort" -H "Content-Type: application/json" -d "{\"TotalEDInpatientVisits\":{\"operator\":\"=\",\"value\":0}}"
```

**Comment by xu-hao** [comment]
Second query:
```
curl -k -XPOST https://icees.renci.org:16339/patient/2016/cohort/COHORT:19/feature_association -H "Content-Type: application/json" -d "{\"feature_a\":{\"Race\":{\"operator\":\"=\",\"value\":\"African American\"}},\"feature_b\":{\"AvgDailyPM2.5Exposure_StudyAvg_qcut\":{\"operator\":\"<\", \"value\":3}}}"
```

**Comment by karafecho** [comment]
So, the first query runs, but the second one does not. Error is: "The filename, label name, or volume label syntax is incorrect".

**Comment by karafecho** [comment]
Also, using the Swagger interface, this query:

![image](https://user-images.githubusercontent.com/26254388/83199529-65a33e80-a10f-11ea-9b96-9c54ba82cec3.png)

Returns this response, which seems incorrect to me:

![image](https://user-images.githubusercontent.com/26254388/83199563-79e73b80-a10f-11ea-892b-aa86f2cd61e8.png)

**Comment by karafecho** [comment]
There's definitely a Windows issue, but I don't think it's related to the need to include \'s in a query because this query runs just fine: curl -X POST "https://icees.renci.org:16339/patient/2016/cohort" -H "accept: application/json" -H "Content-Type: application/json" -d "{}".

**Comment by karafecho** [comment]
Also, I see that you refactored the endpoint. Thanks! Why is that I don't have to specify version number in a CURL?

**Comment by xu-hao** [comment]
Yes, no need to specify version number for v3. this is based on @patrickkwang 's work.

It turns out that the reason no data is returned is because exposure data set 1 is not available for that year. the exposure data set 2 is available: 

```
{"feature_a":{"ace":{"operator":"=","value":"African American"}},"feature_b":{"AvgDailyPM2.5Exposure_2_qcut":{"operator":"<", "value":3}}}```

This should work in the swagger ui,.

**Comment by karafecho** [comment]
Great! Thanks, @xu-hao and @patrickkwang .
