### ISSUE TITLE
Testing k8 deployments

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#223]
This issue is to report results from a systemic testing of the development and production version of the ICEES asthma, DILI, and PCD instances.

**Comment by karafecho** [comment]
***ICEES DILI - development***

- [X] cohort creation
- [X] dictionary 
- [ ] feature association
- [ ] association to all features
- [ ] features
- [X] identifiers
- [X] bins
- [X] year

**Notes:**

1. Feature association returned a 111 error.

Text/tabular output selected

![image](https://user-images.githubusercontent.com/26254388/155157448-bd86d278-b5c3-431a-9176-3844a53be0ed.png)

JSON output selected

![image](https://user-images.githubusercontent.com/26254388/155160242-d05a67bf-7d83-4bd3-b757-7be7b5280dce.png)

2. Association to all features returned a 111 error.

Text/tabular output selected

![image](https://user-images.githubusercontent.com/26254388/155157888-990ce9da-c679-41ff-a5fc-3d5e88f786e1.png)

JSON output selected

![image](https://user-images.githubusercontent.com/26254388/155160494-df37026f-7bea-46a0-bcee-d856628c0983.png)

3. Features returns a 'can't parse JSON' error when JSON output selected.

![image](https://user-images.githubusercontent.com/26254388/155158205-036b75b6-cbd0-455e-8ff8-25febde73eac.png)

4. Features returns an empty table when text/tabular output selected.

![image](https://user-images.githubusercontent.com/26254388/155158601-8170caed-590a-41d8-bda4-5f67263822c0.png)

**Comment by karafecho** [comment]
***ICEES PCD - development***

- [X] cohort creation
- [X] dictionary
- [X] input error 
- [ ] feature association
- [ ] association to all features
- [X] features
- [X] identifiers
- [X] bins
- [X] year

**Notes:**

1. Feature association returns a 111 error.

![image](https://user-images.githubusercontent.com/26254388/155165425-6484b547-780d-4ef7-bff0-8a51aec07375.png)

2. Association to all features returns a 111 error.

![image](https://user-images.githubusercontent.com/26254388/155165582-5372d1f2-5f7d-41cd-801c-5118a1a75008.png)

3. Features works as expected.

![image](https://user-images.githubusercontent.com/26254388/155165935-d8ea175f-af77-4209-a65b-2e696352fb92.png)

**Comment by karafecho** [comment]
Okay, I ran additional tests and updated by checklists.

WRT the 'cannot parse JSON' error, I'm not entirely convinced that it is a Swagger UI issue because it is only affecting the ICEES DILI dev instance (not the ICEES Asthma dev or ICEES PCD dev instances). I've created #225.

WRT the bin error, I've created #226.

**Comment by karafecho** [comment]
(didn't mean to close with comment just yet)

**Comment by hyi** [comment]
@karafecho Yes, please close this issue. Looks like the remaining issues have already been captures in new issues which I don't think are related to Sterling deployment.

**Comment by karafecho** [comment]
Closing issue.

**Comment by karafecho** [comment]
***ICEES SEP2020 COVID - development***

- [X] cohort creation
- [X] dictionary
- [X] input error 
- [X] feature association
- [] association to all features
- [] features
- [X] identifiers
- [X]  bins
- [X] year

**Notes**:

1. AgeStudyStart and AgeStudyStart2 are coded incorrectly. This reflects an error in the formatting of the csv file, which appears to have been introduced when creating the SQLite db. We can fix this when we deploy the JAN2021 instance.

2. The "Features" functionality initially kept timing out (not atypical), but when it finally worked, it yielded empty results, meaning that every feature contained empty cells or NaN. Note that I was only able to run this using COHORT:1; COHORT:2 repeatedly timed out.

Here's an example query: curl -X 'GET' \
  'https://icees-covid-dev.apps.renci.org/patient/cohort/COHORT%3A1/features' \
  -H 'accept: text/tabular'

3. The "Association to all features" functionality ran correctly when I used COHORT:1, but it returned an error when I used COHORT:2. Note that this test was run to see if I encountered the same error noted in #228.

curl -X 'POST' \
  'https://icees-covid-dev.apps.renci.org/patient/cohort/COHORT%3A2/associations_to_all_features' \
  -H 'accept: text/tabular' \
  -H 'Content-Type: application/json' \
  -d '{
  "feature": {
    "TotalEDInpatientVisits": {
      "operator": "=",
      "value": "0"
    }
  },
  "maximum_p_value": 1,
  "correction": {
    "method": "bonferroni"
  }
}'

![image](https://user-images.githubusercontent.com/26254388/158208500-f9ec750c-a9b2-475f-8843-02c30e2477e3.png)

**Comment by hyi** [comment]
@karafecho I believe this issue can be closed as well for now.
