### ISSUE TITLE
Formatting issue with API output for ICEES PCD instance

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#229]
This issue is to report a formatting issue with the output from the ICEES PCD instance. The issue applies specifically to the variables AgeAtStudyStart and AgeAtStudyStart2, in which the ages for years 3-17 are being returned as 17-Mar. The impact is that all other functionalities that return age data incorrectly assume that ages for years 3-17 are null.

I'm pretty sure that this issue relates to the formatting issues that Hong encountered when converting the csv data file to another format.

![image](https://user-images.githubusercontent.com/26254388/157776877-dcccf497-a648-400f-b1ed-8d86db6528d9.png)

**Comment by hyi** [comment]
Verified these mis-formatted dates, 17-Mar and 17-May, come from PCD patient csv files, so the patient csv files need to be fixed going forward.

**Comment by hyi** [comment]
@karafecho I believe this issue can be closed for now.

**Comment by karafecho** [comment]
Issue resolved and can now be closed.
