### ISSUE TITLE
consolidate v1 to v3 data

### ISSUE THREAD

**Issue by xu-hao** [NCATS-Tangerine/icees-api#23]
Currently, v3 is running on port 16339 while v1 and v2 are running on port 80. 

v1 and v2 are using the url patterns
https://icees.renci.org/<version\>/

v3 is using the url pattern
https://icees.renci.org:16339/

We should consolidate them so they all run under the port 80. 

Solution: Put all three versions behind nginx.

**Comment by patrickkwang** [comment]
@karafecho is this still relevant?
