### ISSUE TITLE
'knowledge_graph' versus 'query_graph'

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#32]
Per @bizon@renci.org, please change 'query_graph' to 'knowledge_graph' and then update the examples provided here and also posted in [this doc](https://docs.google.com/document/d/1Vcpp6ehoq_Ba4NmdRkpSGnWfACfDo4owYqC10hQlE2I/edit?usp=sharing).

**Comment by patrickkwang** [comment]
OBE
