### ISSUE TITLE
Bin Values

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#37]
A somewhat pressing issue is to develop an approach for returning bin values (e.g., bin cut-off points for PM2.5) to users or to otherwise provide that documentation. Otherwise, users will need to contact you/me to obtain this info.

**Comment by mmersmann** [comment]
"features" endpoint is the best place to include this information

**Comment by karafecho** [comment]
@patrickkwang : Where do we stand on this?

**Comment by mmersmann** [comment]
**Update:** Patrick to begin work on bin values for returned/called features.

**Comment by mmersmann** [comment]
**Update:** Patrick has cleaned up updates to move ICEES API into FastAPI framework, which was necessary before adding this extra endpoint.
**Next Steps:** Patrick needs to know how to access the output data. Data will have to be sent to Patrick because he can't access Rockfish.

**Comment by mmersmann** [comment]
**Next Steps:** @xu-hao to provide necessary data to @patrickkwang

**Comment by mmersmann** [comment]
**Update:** Emily has reviewed and signed off on the data to be sent to Patrick et al. Hao sending today.

**Comment by mmersmann** [comment]
**Update:** Bin values available [here](https://icees.renci.org:16340/apidocs#/default/handle_bins_bins_get
).
**Next steps:** 
1. Kara to review documentation.
2. (As needed) Create a new endpoint based on bin values.

**Comment by patrickkwang** [comment]
#55
