### ISSUE TITLE
Counts related to ED, Inpatient, ED/Inpatient, etc.

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#44]
The counts aren't necessarily making sense.

Action: Review scenarios and reach out to James/Emily if needed.

**Comment by karafecho** [comment]
Tables were validated against raw data.

Skew relates to Active_In_Year, the treatment of single-year data pulls versus multi-year data pulls, as well as the fact that the 2010 and 2011 tables were generated from an earlier batch than the tables from later years.

**Comment by karafecho** [comment]
**SUMMARY:**

**COHORT:4 (Active_In_Year = 1, created in year 2010)**

*2016*
ED 19550, 748, 545,...
Inpatient 21881, 517, 156,...
ED/Inpatient 19547, 734, 547,...

*2010*
ED 13877, 3562, 1429,...
Inpatient 18796,3500,469,...
ED/Inpatient 640, 15059, 4002 ...

**COHORT:98 (Active_In_Year = 1, created in year 2016)**

*2016*
ED 4866, 17637, 10565,...
Inpatient 40747, 10569, 2193,...
ED/Inpatient 4585, 17609, 10634,...

*2010*
ED 51342, 1818, 698,...
Inpatient 53926, 641, 116,...
ED/Inpatient 51069, 1911, 752,...

**COHORT:3 (all, created in year 2010)**

*2016*
ED 107516, 17638, 10567,...
Inpatient 143401, 10571, 2194,...
ED/Inpatient 107235, 17610, 10636,...

*2010*
ED 139057, 13879, 3564,...
Inpatient 155126, 3500, 469,...
ED/Inpatient 136966, 15061, 4004,...

**COHORT:101 (all, created in year 2016)**

*2016*
ED 107516, 17638, 10567,...
Inpatient 143401, 10571, 2194,...
ED/Inpatient 107235, 17610, 10636,...

*2010*
ED 137394, 13720, 3504,...
Inpatient 153287, 3434, 459,...
ED/Inpatient 135353, 14867, 3938,...

COHORT:3 n=163266 and COHORT:101 n=161348. Theoretically, the cohorts should be identical. Difference is due to patients with age >= 90 in 2016 but age < 90 in 2010.

**Comment by karafecho** [comment]
Other options for Active_In_Year are under review.

**Comment by karafecho** [comment]
10.26.20: Confirmed with Emily and James that our approach for calculating Active_In_Year is valid.

From Hao, 10.21.20:

Currently, we take the union of all pids from all years. and generate a row for each pid for every year. The Active_In_Year feature in icees tables is calculated from the Patient resources. For each year, the pids in the Patient resources in that year have value 1, pids not in the Patient resources in that year have value 0.

I'm working on a new version which doesn't depend on the patient resource. Rather, it looks at other resources in the dataset. The interpretation is that: if Active_In_Year is 0 for a pid in a year, then there is no Medication/Condition/Diagnosis/Encounter/Lab/etc for that patient in that year in the dataset. Otherwise, then there is at least one Medication/Condition/Diagnosis/Encounter/Lab/etc for that patient in that year in the dataset.

**Comment by karafecho** [comment]
Validated data.

Confirmed with Emily and James on 10.26.20 that current approach is appropriate.

**Comment by karafecho** [comment]
I'd like to keep this issue active, just until we find another way to track issues such as this.

**Comment by patrickkwang** [comment]
Sorry, I must have misread this and thought this issue was resolved. It has been moved here: https://github.com/ResearchSoftwareInstitute/icees-phase-2/issues/125
