### ISSUE TITLE
Exposures bins - patient table, 2016

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#51]
This purpose of this issue is to obtain bin values for the following variables (patient table, 2016): EstResidentialDensity, EstHouseholdIncome, AvgDailyPM2.5Exposure_2, AvgDailyPM2.5Exposure_qcut, MaxDailyOzoneExposure_2, MaxDailyOzoneExposure_2_qcut. This is for a *JACI* manuscript I am developing with Dave Peden. Target submission date is December 4, 2020.

**Comment by patrickkwang** [comment]
Let's find another venue for tracking tasks like this.
