### ISSUE TITLE
API endpoints for bin values

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#52]
Email exchange on November 17, 2020:

The bin values for the other variables can be found in the YAML file that Priya created. (Note that the binning for CAFO_Distance, LandfillDistance, and PublicSchoolDistance may need modification or are TBD.)

And also here, here, here, and here.

I apologize for the disjointed email. I have been attending the AMIA 2020 Virtual Annual Symposium this week and am a bit distracted.

If a meeting would be helpful to discuss the plan and next steps, please let me know.

Thanks again,

Kara

On Tuesday, November 17, 2020, 9:48:42 PM EST, Karamarie Fecho, PhD <kfecho@copperlineprofessionalsolutions.com> wrote:

Patrick, Max,

Thanks for offering to create API endpoints to expose the binning values for ICEES+ feature variables.

The relevant exposures files can be accessed here:

(1) airborne pollutant data (eight exposures) from most recent pull, 2002-2016
this can be accessed from most RENCI machine (for example vm) /projects/datatrans/new_cmaq_data/merged_cmaq_.csv*
(2) ACS socioeconomic data for both sampling periods, 2007-2011, 2012-2016
this is on rockfish: /var/fhir/other/acs/ACS_NC_2016_with_column_headers.csv has all variables but ur in /var/fhir/other/acs/Appold_trans_geo_cross_02.10.10 - trans_geo_cross.csv

The bins are based on pandas.cut and pandas.qcut for (1) and pandas.qcut for (2). The bin values for the other variables can be found in the YAML file that Priya created. (Note that the binning for CAFO_Distance, LandfillDistance, and PublicSchoolDistance may need modification or are TBD.)

Priya,

Please confirm that you've updated your pull request for the YAML file. The last update that I saw was from 8 days ago.

Lisa,

I believe you have access to the files for (1) and (2). Assuming that's correct, please transfer them to Patrick and Max.

**Comment by karafecho** [comment]
The bin values for the other variables can be found in the YAML file that Priya created. (Note that the binning for CAFO_Distance, LandfillDistance, and PublicSchoolDistance may need modification or are TBD.)

And also here, here, here, and here.

I apologize for the disjointed email. I have been attending the AMIA 2020 Virtual Annual Symposium this week and am a bit distracted.

If a meeting would be helpful to discuss the plan and next steps, please let me know.

Thanks again,

Kara

**Comment by karafecho** [comment]
ICEES+ COVID-19 (deidentified, binned) table location on Rockfish: /opt/RENCI/output/icees/COVID/v1

files with no extensions are the csv files
.json files contain bin values for feature variables

**Comment by patrickkwang** [comment]
#55
