### ISSUE TITLE
ICEES+ COVID-19 FHIR files transferred from Rockfish to Cadence server

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#58]
This issue is intended to transfer ICEES+ COVID-19 FHIR files from Rockfish to Cadence server, using protocol and process agreed to by NC TraCS/SOM. James to complete this task after permissions have been updated.

**Comment by karafecho** [comment]
For the covid dataset
COVID/covid.dhall
1. config dir, default: /share/spark/hao/datatrans/spark/config/COVID
2. input dir, default: /var/fhir/COVID
3. temp dir, default: /share/spark/hao/data/COVID
4. output dir, default /share/spark/hao/data/COVID

**Comment by karafecho** [comment]
Binned, de-identified ICEES+ integrated feature tables should also be transferred to the Cadence server.

**Comment by davidborland** [comment]
Any update on getting this data copied over to our Cadence server? Thanks.

**Comment by mmersmann** [comment]
@karafecho Can you weigh in here?

**Comment by karafecho** [comment]
@davidborland : please see [this issue](https://github.com/ResearchSoftwareInstitute/icees-covid-19/issues/27) and note the list of IRB-approved personnel.

Related, have you worked with @stevencox and @mmersmann to gain access to the deidentified, binned ICEES+ integrated feature tables on ebcr0.edc.renci.org. This shouldn't take long and will allow you to see all of the ICEES+ tables, including the one partial table that we've generated for the ICEES+ COVID-19 project.

**Comment by mmersmann** [comment]
@karafecho: David B., Lisa, David G., and James should all have access to ebcr0.edc.renci.org.  I'll follow up with David B. via email to make sure he's squared away.

**Comment by davidborland** [comment]
I've been able to view the data there. I think it would be a good idea to set up a call with myself, David Gotz, and anyone else it makes sense to include to go over the different files and fields and plan what might make sense as a first pass for trying to ingest into Cadence.

**Comment by karafecho** [comment]
@mmersmann : Please copy me on matters such as this, or otherwise inform me, so that I know things are resolved.

@davidborland :
I think a meeting makes sense, but it may be hard to schedule, as a few of us will be attending a Translator meeting all next week. In the meantime, I would use the files on ebcr0.edc.renci.org as a way to become familiar with ICEES+. 

I think the plan for Cadence is to explore the patient data that is used to generate the ICEES+ tables at ebcr0.edc.renci.org and determine if there are better ways to expose and explore the data, while maintaining compliance with all regulatory and institutional requirements. I'm especially interested in approaches to expose and explore longitudinal data. Our existing approach is limited at best. 

One other thing that may be helpful for data exploration is the [ICEES+ UI](http://robokop.renci.org:11633/).

We can certainly schedule a meeting, but I hope the above info helps in the meantime.

**Comment by karafecho** [comment]
@mmersmann : In terms of a meeting, I'd suggest David B., David G., James, Chris B., and me.

**Comment by patrickkwang** [comment]
This is an upstream/deployment issue that should not be discussed here.
