### ISSUE TITLE
EstResidentialDensity and ur, v2.0.0, year 2010

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#6]
Something seems off with the binning for EstResidentialDensity and ur, v2.0.0, year 2010.  I think they should be the same, since EstResidentialDensity = 3 (urbanized area) does not exist within this cohort? In other words, (EstResidentialDensity = 1) = (ur = R)?

![image](https://user-images.githubusercontent.com/26254388/64650923-55ff9080-d3ee-11e9-9cf8-be1f68fb8ddd.png)

![image](https://user-images.githubusercontent.com/26254388/64650948-631c7f80-d3ee-11e9-98c5-41b385200879.png)

**Comment by karafecho** [comment]
I thought we calculated "ur" based on "EstResidentialDensity", when we expected to see patients with "EstResidentialDensity = 3"?

**Comment by patrickkwang** [comment]
Upstream issue.
