### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#61]
This issue is intended to address or correct apparent 422 validation errors in the response body of ICEES API requests. For instance, I'm receiving the apparent error below, even when running a successful query. This may be nothing, but I haven't encountered the error previously.

![image](https://user-images.githubusercontent.com/26254388/104398592-0b7bb000-551d-11eb-87bb-a8436e9488b3.png)

**Comment by patrickkwang** [comment]
OBE
