### ISSUE TITLE
API troubleshooting

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#69]
Create cohort: Active_In_Year=1, N = 22,954 , COHORT:291

Create cohort: {}, year 2019, N=161,911, COHORT:3

Create cohort: {}, year 2018, N = 162,691, COHORT:13

Create cohort: {}, year 2017, N = 163,392, COHORT:14

Create cohort: {}, year 2016, N = 163,986, COHORT:12

Create cohort: {}, year 2015, N 164,493, COHORT:15

Create cohort: {}, year 2014, N = 164,909, COHORT:16

Create cohort: {}, year 2013, N =165,244, COHORT:17

Create cohort: {}, year 2012, N = 165,517, COHORT:18

Create cohort: {}, year 2011, N = 165,746, COHORT:19

Create cohort: {}, year 2010, N = 165,904, COHORT:11

Create cohort: Sex2 = M, year 2019, N = 68,544, COHORT:9

Create cohort: Sex2 = F, year 2019, N = 90,783, COHORT:10

COHORT:9 + COHORT:10 = 159,327

Create cohort: AgeStudyStart 0-2, year 2019, N = 100, COHORT:4

Create cohort: AgeStudyStart 0-2, year 2018, N = 667, COHORT:6

Create cohort: AgeStudyStart 0-2, year 2017, N = 1704, COHORT:7

Create cohort: AgeStudyStart 0-2, year 2016, N = 2838, COHORT:8

Create cohort: AgeStudyStart 0-2, year 2015, N = 4079 , COHORT:289

Create cohort: AgeStudyStart 0-2, year 2014, N = 5638, COHORT:288

Create cohort: AgeStudyStart 0-2, year 2013, N = 7607, COHORT:287

Create cohort: AgeStudyStart 0-2, year 2012, N = 9602, COHORT:286

Create cohort: AgeStudyStart 0-2, year 2011, N = 11,467, COHORT:285

Create cohort: AgeStudyStart 0-2, year 2010, N = 13,266, COHORT:2

Create cohort: AgeStudyStart <>0-2, year 2019, N = 155,237, COHORT:290

Create cohort: Active_In_Year=1, N = 22,954 , COHORT:291

Create cohort: AgeStudyStart 0-2, Active_In_Year=1, year 2019, N = 11, COHORT:292

Create cohort: AgeStudyStart <>2, Active_In_Year=1, year 2019, N = 22,943, COHORT:293

![image](https://user-images.githubusercontent.com/26254388/107248735-95c21180-6a00-11eb-99ac-7242b6c2e858.png)

![image](https://user-images.githubusercontent.com/26254388/107248294-277d4f00-6a00-11eb-8169-1ddf474ddea6.png)

![image](https://user-images.githubusercontent.com/26254388/107249392-52b46e00-6a01-11eb-8817-455f059028d4.png)

![image](https://user-images.githubusercontent.com/26254388/107249437-5d6f0300-6a01-11eb-956f-7f6a7a1abd3d.png)

![image](https://user-images.githubusercontent.com/26254388/107249819-b50d6e80-6a01-11eb-81c3-bf898e6f2f9c.png)

![image](https://user-images.githubusercontent.com/26254388/107249892-bd65a980-6a01-11eb-88de-6f136cda4c99.png)

![image](https://user-images.githubusercontent.com/26254388/107250455-e8e89400-6a01-11eb-8adb-846d6ed85cc0.png)

![image](https://user-images.githubusercontent.com/26254388/107250641-f69e1980-6a01-11eb-9573-e27e8b709713.png)

**Comment by karafecho** [comment]
@patrickkwang : The above tests seem to be producing correct results. However, it looks like we have not updated our patient catchment since the original data pull. There are pros and cons to this, I think. @epfaff@email.unc.edu, @champioj@email.unc.edu, @ashok@renci.org : what do you all think?

**Comment by karafecho** [comment]
Well, after additional troubleshooting added to the above, I now think we have a few different issues.

**Comment by patrickkwang** [comment]
Sounds like an upstream data-generation issue.
