### ISSUE TITLE
Updates to SmartAPI registration

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#72]
This issue is to update the SmartAPI registration by including the following:

1. Contact info
info:
  contact:
    email: patrick@covar.com
    name: Patrick Wang
    url: https://github.com/NCATS-Tangerine/icees-api/tree/master/
    x-role: responsible developer
2. Translator tagging
  x-translator:
    component: KP
    team:
    - Exposures Provider
3. One-hop endpoint (and I don't know how to add this)

**Comment by patrickkwang** [comment]
Can you clarify "one-hop endpoint"? We have one.

**Comment by karafecho** [comment]
Yes, it looks like the KG endpoint is the only one registered as a KG endpoint. All of the other paths are for the non-KG endpoints. 

BTW, Kevin included a comment on predicates that was similar to Noel's comment. I think there may be some general confusion surrounding the clinical KPs.

**Comment by karafecho** [comment]
Complete.
