### ISSUE TITLE
Timeout Error with 2010-2014 nine feature tables

### ISSUE THREAD

**Issue by BLan1211** [NCATS-Tangerine/icees-api#76]
@karafecho 
1. The query results in a timeout error.  Running the same query multiple times for each year from 2010 to 2014 produces different results for the same year, respectively.

For instance, for year 2010:
1st query: 42102 rows
2nd query: 15462 rows
3rd query: 20124 rows

2. The first few rows of the queried data are shown below. As you can see, the “frequency” column is blank.

![image](https://user-images.githubusercontent.com/66024378/108663522-c2fdcd80-749e-11eb-9e16-63c7e5f74e82.png)

3. The errors did not occur at the beginning.  In fact, they occurred at the very bottom in the log window.   Below are the errors:
……………………………………………….
	[4:28.54]	18 rows made
	[4:30.78]	18 rows made
	[4:33.59]	18 rows made
	[4:36.6]	18 rows made
	[4:37.73]	18 rows made
	[4:38.85]	18 rows made
	[4:40.02]	18 rows made
	[4:41.15]	18 rows made
	[4:42.35]	18 rows made
	[4:44.07]	18 rows made
	[4:45.27]	18 rows made
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
~\anaconda3\lib\site-packages\urllib3\connection.py in _new_conn(self)
    156             conn = connection.create_connection(
--> 157                 (self._dns_host, self.port), self.timeout, **extra_kw
    158             )

~\anaconda3\lib\site-packages\urllib3\util\connection.py in create_connection(address, timeout, source_address, socket_options)
     83     if err is not None:
---> 84         raise err
     85 

~\anaconda3\lib\site-packages\urllib3\util\connection.py in create_connection(address, timeout, source_address, socket_options)
     73                 sock.bind(source_address)
---> 74             sock.connect(sa)
     75             return sock

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
~\anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    671                 headers=headers,
--> 672                 chunked=chunked,
    673             )

~\anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    375         try:
--> 376             self._validate_conn(conn)
    377         except (SocketTimeout, BaseSSLError) as e:

~\anaconda3\lib\site-packages\urllib3\connectionpool.py in _validate_conn(self, conn)
    993         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
--> 994             conn.connect()
    995 

~\anaconda3\lib\site-packages\urllib3\connection.py in connect(self)
    299         # Add certificate verification
--> 300         conn = self._new_conn()
    301         hostname = self.host

~\anaconda3\lib\site-packages\urllib3\connection.py in _new_conn(self)
    168             raise NewConnectionError(
--> 169                 self, "Failed to establish a new connection: %s" % e
    170             )

NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001B5D027FF08>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
~\anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

~\anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    719             retries = retries.increment(
--> 720                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    721             )

~\anaconda3\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    435         if new_retry.is_exhausted():
--> 436             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    437 

MaxRetryError: HTTPSConnectionPool(host='icees.renci.org', port=16340): Max retries exceeded with url: /patient/2010/cohort/COHORT:44/feature_association2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B5D027FF08>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-40-bc5434a834a8> in <module>
      4               QueryStep(stepsjson[8])]
      5 
----> 6 x = QueryFull(query_steps,write_to_csv=CSV_NAME)

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in __init__(self, query_steps, make_unknowns_zero, write_to_csv, print_help, print_debug, year)
    396                 print(ab)
    397             arr = query_steps[:-2]
--> 398             self.data = recursive_loop(arr,df,0,[],colreduced,ab_data=ab,year=year)
    399 
    400         print("QueryFull initialized.")

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_loop(arr, df, index, combination, colnames, ab_data, year)
    323 
    324                     newcomb.append(queryfulldata)
--> 325                     newdf = newdf.append(recursive_loop(arr,df,index+1,newcomb,colnames,ab_data,year),ignore_index=True)
    326                 return newdf
    327 

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_loop(arr, df, index, combination, colnames, ab_data, year)
    323 
    324                     newcomb.append(queryfulldata)
--> 325                     newdf = newdf.append(recursive_loop(arr,df,index+1,newcomb,colnames,ab_data,year),ignore_index=True)
    326                 return newdf
    327 

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_loop(arr, df, index, combination, colnames, ab_data, year)
    323 
    324                     newcomb.append(queryfulldata)
--> 325                     newdf = newdf.append(recursive_loop(arr,df,index+1,newcomb,colnames,ab_data,year),ignore_index=True)
    326                 return newdf
    327 

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_loop(arr, df, index, combination, colnames, ab_data, year)
    323 
    324                     newcomb.append(queryfulldata)
--> 325                     newdf = newdf.append(recursive_loop(arr,df,index+1,newcomb,colnames,ab_data,year),ignore_index=True)
    326                 return newdf
    327 

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_loop(arr, df, index, combination, colnames, ab_data, year)
    323 
    324                     newcomb.append(queryfulldata)
--> 325                     newdf = newdf.append(recursive_loop(arr,df,index+1,newcomb,colnames,ab_data,year),ignore_index=True)
    326                 return newdf
    327 

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_loop(arr, df, index, combination, colnames, ab_data, year)
    323 
    324                     newcomb.append(queryfulldata)
--> 325                     newdf = newdf.append(recursive_loop(arr,df,index+1,newcomb,colnames,ab_data,year),ignore_index=True)
    326                 return newdf
    327 

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_loop(arr, df, index, combination, colnames, ab_data, year)
    323 
    324                     newcomb.append(queryfulldata)
--> 325                     newdf = newdf.append(recursive_loop(arr,df,index+1,newcomb,colnames,ab_data,year),ignore_index=True)
    326                 return newdf
    327 

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_loop(arr, df, index, combination, colnames, ab_data, year)
    293                 #9 is always an upper bound
    294                 if cohortid == None:
--> 295                     bound = recursive_bound(combination,colnames,ab_data,year)
    296                     if bound == None:
    297                         print("Bound was unexpectedly None")

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_bound(combination, colnames, ab_data, year, dif)
    213 
    214             if cohortid == None:
--> 215                 return recursive_bound(combination,colnames,ab_data,year,dif=dif+1)
    216             else:
    217                 #make a new ab_data object from the next two features in line and build a table from there

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_bound(combination, colnames, ab_data, year, dif)
    213 
    214             if cohortid == None:
--> 215                 return recursive_bound(combination,colnames,ab_data,year,dif=dif+1)
    216             else:
    217                 #make a new ab_data object from the next two features in line and build a table from there

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_bound(combination, colnames, ab_data, year, dif)
    213 
    214             if cohortid == None:
--> 215                 return recursive_bound(combination,colnames,ab_data,year,dif=dif+1)
    216             else:
    217                 #make a new ab_data object from the next two features in line and build a table from there

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in recursive_bound(combination, colnames, ab_data, year, dif)
    241 
    242                     feature_enum_list = feature_list_from_combination(combination)
--> 243                     df = generate_nvariate_table(cohortid, new_ab, colnames, feature_enum_list,year)
    244 
    245                     #note that since a/b features are restricted to values selected in the combination,

D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in generate_nvariate_table(cohortid, ab_query, colnames, feature_enum_list, year)
     38     headers = {"Content-Type" : "application/json", "accept": "application/json"}
     39     icees_url = 'https://icees.renci.org:16340/patient/' + str(year) + '/cohort/' + str(cohortid) + '/feature_association2'
---> 40     responsepkt = requests.post(icees_url,headers=headers, data=ab_query, verify=False)
     41     if responsepkt.status_code != 200:
     42         print("Request failed {0}\n{1}\n{2}\n{3}".format(responsepkt.status_code, responsepkt.reason, responsepkt.request, responsepkt.text))

~\anaconda3\lib\site-packages\requests\api.py in post(url, data, json, **kwargs)
    114     """
    115 
--> 116     return request('post', url, data=data, json=json, **kwargs)
    117 
    118 

~\anaconda3\lib\site-packages\requests\api.py in request(method, url, **kwargs)
     58     # cases, and look like a memory leak in others.
     59     with sessions.Session() as session:
---> 60         return session.request(method=method, url=url, **kwargs)
     61 
     62 

~\anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    531         }
    532         send_kwargs.update(settings)
--> 533         resp = self.send(prep, **send_kwargs)
    534 
    535         return resp

~\anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    644 
    645         # Send the request
--> 646         r = adapter.send(request, **kwargs)
    647 
    648         # Total elapsed time of the request (approximately)

~\anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='icees.renci.org', port=16340): Max retries exceeded with url: /patient/2010/cohort/COHORT:44/feature_association2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B5D027FF08>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by BLan1211** [comment]
import pandas as pd
import sys
sys.path.insert(1, 'D>/BL/Renci/icees-kp-analytics/Python-BL')
from Query import QueryStep, QueryFull, generate_cohort

stepsjson = [  
            '''{
        "Active_In_Year":[
                        {"operator":"=","value":1}
                    ]
                    }''',
    '''{
        "TotalEDInpatientVisits":[
                        {"operator":"=","value":0},
                        {"operator":"=","value":1},
                        {"operator":"=","value":2},
                        {"operator":"=","value":3},
                        {"operator":"=","value":4},
                        {"operator":"=","value":5},
                        {"operator":"=","value":6},
                        {"operator":"=","value":7},
                        {"operator":"=","value":8},
                        {"operator":"=","value":9},
                        {"operator":">","value":9}
                    ]
                    }''',
    '''
        {
        "Sex2":[
                {"operator": "=", "value": "Male"},
                {"operator": "=", "value": "Female"}
        
                ]
                }''',
    
    ''' 
        {
        "Race":[
                {"operator": "=", "value": "Native Hawaiian/Pacific Islander"},
                {"operator": "=", "value": "Caucasian"},
                {"operator": "=", "value": "African American"},
                {"operator": "=", "value": "Asian"},
                {"operator": "=", "value": "Unknown"},
                {"operator": "=", "value": "American/Alaskan Native"},
                {"operator": "=", "value": "Other"}
                
                ]
                }''',
    '''
        {
        "Prednisone":[
                {"operator": "=", "value": 0},
                {"operator": "=", "value": 1}
        
                ]
                }''',
    
     '''
        {
        "ObesityDx":[
                {"operator": "=", "value": 0},
                {"operator": "=", "value": 1}
        
                ]
                }''',
 
    
    '''{
        "MaxDailyPM2.5Exposure_StudyMax":[
                        {"operator":"=","value":1}, 
                        {"operator":"=","value":2}, 
                        {"operator":"=","value":3},
                        {"operator":"=","value":4},
                        {"operator":"=","value":5} 
                    ]
                    }''',      
        '''{
        "RoadwayDistanceExposure2":[
                {"operator": "=", "value": 1},
                {"operator": "=", "value": 2},
                {"operator": "=", "value": 3},
                {"operator": "=", "value": 4},
                {"operator": "=", "value": 5},
                {"operator": "=", "value": 6}
                
                ]
                }''',   
    '''{
        "EstResidentialDensity":[
                {"operator": "=", "value": 1},
                {"operator": "=", "value": 2},
                {"operator": "=", "value": 3}
                
                ]
                }'''
  
        ]

CSV_NAME = "data/yr2010_7vars.csv"
query_steps = [QueryStep(stepsjson[0]),QueryStep(stepsjson[1]), QueryStep(stepsjson[2]), QueryStep(stepsjson[3]),
              QueryStep(stepsjson[4]),QueryStep(stepsjson[5]),QueryStep(stepsjson[6]),QueryStep(stepsjson[7]),
              QueryStep(stepsjson[8])]

x = QueryFull(query_steps,write_to_csv=CSV_NAME)




# #####Query######
# -*- coding: utf-8 -*-
from typing import List, Dict, Tuple, Sequence
import requests
import sys
import numpy as np
import pandas as pd
import json
import math
import time

def generate_cohort(jsonCohortQuery,year):
    requests.packages.urllib3.disable_warnings()
    headers = {"Content-Type" : "application/json", "accept": "application/json"}
    responsepkt = requests.post('https://icees.renci.org:16340/patient/' + str(year) + '/cohort', headers=headers, data=jsonCohortQuery, verify=False)
    if responsepkt.status_code != 200:
        print("Request failed {0}\n{1}\n{2}\n{3}".format(responsepkt.status_code, responsepkt.reason, responsepkt.request, responsepkt.text))
        sys.exit(-1)

    try:
        return_id = responsepkt.json()['return value']['cohort_id']
        return return_id
    except:
        return None

def generate_cohort_from_combination(combination,year):
    cohortobj = {}
    for k in range(0,len(combination)):
        dataobj = json.loads(combination[k])
        key = list(dataobj.keys())[0]
        cohortobj[key] = dataobj[key]
    
    cohortstr = json.dumps(cohortobj)
    cohortid = generate_cohort(cohortstr,year)
    return cohortid

def generate_nvariate_table(cohortid, ab_query, colnames, feature_enum_list, year):
    requests.packages.urllib3.disable_warnings()
    headers = {"Content-Type" : "application/json", "accept": "application/json"}
    icees_url = 'https://icees.renci.org:16340/patient/' + str(year) + '/cohort/' + str(cohortid) + '/feature_association2'
    responsepkt = requests.post(icees_url,headers=headers, data=ab_query, verify=False)
    if responsepkt.status_code != 200:
        print("Request failed {0}\n{1}\n{2}\n{3}".format(responsepkt.status_code, responsepkt.reason, responsepkt.request, responsepkt.text))
        sys.exit(-1)

    try:
        tbldict = responsepkt.json()['return value']['feature_matrix']      # returns a list [frequency, total_per, row_per, col_per]
    except:
        print(responsepkt.json())
        raise Exception("Problem when generating bivariate table")
    blen = len(tbldict)
    alen = len(tbldict[0])
    
    a_step = QueryStep(json.loads(ab_query)["feature_a"])
    b_step = QueryStep(json.loads(ab_query)["feature_b"])

    # now convert the json frequency values to a matrix
    df = pd.DataFrame(index=np.arange(alen*blen), columns=colnames)

    #setting first n-2 columns according to feature_enum_list
    for i in range(0,len(feature_enum_list)):
        df[colnames[i]] = feature_enum_list[i]

    row=0
    for bindex, trb in enumerate(tbldict):
        for aindex, tra in enumerate(trb):
            #naming a,b cols one row at a time
            df.at[row, colnames[-1:]] = a_step.enum[aindex]
            df.at[row, colnames[-2:-1]] = b_step.enum[bindex]
            
            df.at[row, 'frequency'] = float(tra['frequency'])
            row = row + 1

    return df

#for when it returns bad results with correct input i.e. when cohort size is <10
def generate_none_table(ab_data,colnames,feature_enum_list):
    abobj = json.loads(ab_data)
    df_length = 1
    alen = len(abobj["feature_a"][list(abobj["feature_a"].keys())[0]])
    blen= len(abobj["feature_b"][list(abobj["feature_b"].keys())[0]])
    df_length = df_length * alen * blen
    
    a_step = QueryStep(abobj["feature_a"])
    b_step = QueryStep(abobj["feature_b"])
    
    df = pd.DataFrame(index=np.arange(df_length), columns=colnames)

    for i in range(0,len(feature_enum_list)):
        df[colnames[i]] = feature_enum_list[i]

    for index, row in df.iterrows():
        df.at[index, colnames[-1:]] = a_step.enum[index % alen]
        df.at[index, colnames[-2:-1]] = b_step.enum[math.floor(index / alen)]
        
    df["frequency"] = np.nan
    return df

#determines how the feature-values are named in the CSV's rows
def get_enum_name(feature_name,operator,value):
    s = ""
    feature_map = {
        "RESPONDER_STATUS":"responder",
        "PM25_ANNUAL_AVERAGE_qcut":"pm25_average",
        "MaxDailyPM2.5Exposure_qcut":"pm25_max",
    }
    featurestring = str(feature_name).replace(" ","_").lower()
    
    try:
        featurestring = feature_map[feature_name]
    except:
        pass
    
    valstring = str(value).replace(" ","_").lower()
    if operator == "=":
        s = featurestring + "_" + valstring
    else:
        s = featurestring + operator + valstring
    return s


def extract(n):
    if "value" in n:
        return n["value"]
    elif "values" in n:
        return ",".join(n["values"])
    elif "value_a" in n and "value_b" in n:
        return n["value_a"] + " " + n["value_b"]
    else:
        return None
    
def feature_list_from_combination(combination):
    feature_enum_list = []
    for j in range(0,len(combination)):
        q = json.loads(combination[j])
        k = list(q.keys())[0]
        n = q[k]
        feature_enum_list.append(get_enum_name(k,n["operator"],extract(n)))
    return feature_enum_list

def get_base_cohort(year):
    cohort = generate_cohort("{}",year)
    return cohort

"""
eg

{"RESPONDER_STATUS":[
    {"operator":"=","value":"Hyper"}, 
    {"operator":"=","value":"Hypo"}, 
    {"operator":"=","value":"Super Hypo"}, 
    {"operator":"=","value":"Neither"}
]}
        
step_data can be object or json string
"""
class QueryStep:
    def __init__(self, step_data):
        if step_data == str(step_data):
            self.step_data = json.loads(step_data)
        else:
            self.step_data = step_data
            
        if len(self.step_data) != 1:
            raise ValueError("Must be one feature")
        for key in self.step_data:
            self.feature_name = key
        
        enum = []
        queries = []
        arr = self.step_data[self.feature_name]
        for i in range(0,len(arr)):
            #current_query = json.loads(arr[i])
            current_query = arr[i]
            s = get_enum_name(self.feature_name,current_query["operator"],extract(current_query))
            enum.append(s)
            queries.append(current_query)
        #set of strings for identifying values in the csv
        self.enum = enum
        #the actual steps to iterate over eg {"operator":"=","value":"Hyper"}
        self.queries = queries

    def get_step_string(self):
        return self.feature_name
 
class QueryFull:
    def __init__(self,query_steps,make_unknowns_zero=False,write_to_csv=None,print_help=True,print_debug=False,year=2010):
        self.steps = query_steps
        self.data = pd.DataFrame(index=[0],columns=["frequency"])
        self.year = year

        num_cohorts_made = 0

        start_time = time.time()
        if print_help:
            print("Initializing QueryFull with " + str(len(query_steps)) + " features")
            if len(query_steps) > 2:
                expected_rows = 1
                for i in query_steps:
                    expected_rows *= len(i.queries)
                print("Expected # of rows to generate: " + str(expected_rows))

        def recursive_bound(combination,colnames,ab_data,year,dif=1):
            #combination is the cohort we tried to make but couldn't
            #dif is the number of features recursively cut off from the end of the combination until it works
            reduced_combination = combination[:-dif]
            cohortid = generate_cohort_from_combination(reduced_combination,year)
            
            def combo_to_feature_obj(combo_obj:str) -> dict:
                feature_obj = json.loads(combination[-1])
                b_name = list(feature_obj.keys())[0]
                feature_obj[b_name] = [feature_obj[b_name]]
                return feature_obj

            if cohortid == None:
                return recursive_bound(combination,colnames,ab_data,year,dif=dif+1)
            else:
                #make a new ab_data object from the next two features in line and build a table from there
                #to get upper bound
                if dif == 0:
                    return None
                elif dif == 1:
                    #we shift ab over one
                    #note that feature a is the last while feature b is second to last
                    new_ab = {}
                    old_ab = json.loads(ab_data)
                    new_ab["feature_a"] = old_ab["feature_b"]
                    new_ab["feature_b"] = combo_to_feature_obj(combination[-1])
                    new_ab = json.dumps(new_ab)

                    feature_enum_list = feature_list_from_combination(combination)
                    df = generate_nvariate_table(cohortid, new_ab, colnames, feature_enum_list,year)

                    return df["frequency"].sum()

                elif dif >= 2:
                    #we make a new ab
                    new_ab = {}
                    new_ab["feature_a"] = combo_to_feature_obj(combination[-1])
                    new_ab["feature_b"] = combo_to_feature_obj(combination[-2])
                    new_ab = json.dumps(new_ab)

                    feature_enum_list = feature_list_from_combination(combination)
                    df = generate_nvariate_table(cohortid, new_ab, colnames, feature_enum_list,year)

                    #note that since a/b features are restricted to values selected in the combination,
                    #we do not need to "narrow down" the resulting table
                    #if n>3, it might be expected that the upper bound is less reflective of how big
                    #a cohort made from the first n-2 features could actually be.
                    return df["frequency"].sum()

        def recursive_loop(arr,df,index,combination,colnames,ab_data,year):
            
            if index == len(arr):
                #combination is an array of strings such as '{"Sex2":{"operator":"=","value":"Male"}}'
                #makes a cohort for every possible combination of the first n-2 feature's values
                #the last 2 features are added to the table as ab_data with an nvariate table
                if print_debug:
                    print("combination:")
                    print(combination)
                
                #the names for the feature-values in the csv
                feature_enum_list = feature_list_from_combination(combination)

                if print_debug:
                    print("featureenum")
                    print(feature_enum_list)

                    print("combination")
                    print(combination)

                cohortid = generate_cohort_from_combination(combination,year)

                #this means the cohort is <10 size generally speaking
                if cohortid == None:
                    resdf = generate_none_table(ab_data,colnames,feature_enum_list)
                    if make_unknowns_zero == True:
                        resdf["frequency"] = 0
                else:
                    resdf = generate_nvariate_table(cohortid, ab_data, colnames, feature_enum_list, year)
                
                #making sure frequency column is numeric and not string
                resdf["frequency"] = pd.to_numeric(resdf["frequency"])

                nonlocal num_cohorts_made
                num_cohorts_made += 1
                #not called cohort_id because that's used already by ICEES API
                resdf["cohort_name"] = num_cohorts_made

                if print_debug:
                    print(resdf)

                #establishing upper bounds
                #9 is always an upper bound
                if cohortid == None:
                    bound = recursive_bound(combination,colnames,ab_data,year)
                    if bound == None:
                        print("Bound was unexpectedly None")
                        resdf["cohort_bound"] = 9
                    elif bound < 9:
                        resdf["cohort_bound"] = bound
                    else:
                        resdf["cohort_bound"] = 9
                else:
                    resdf["cohort_bound"] = resdf["frequency"].sum()

                if write_to_csv != None:
                    resdf.to_csv(write_to_csv, mode='a', header=False,index=False)

                if print_help:
                    nonlocal start_time
                    now = time.time() - start_time
                    print("\t[" + str(math.floor(now/60)) + ":" + str(round(now%60,2)) + "]\t" + str(len(resdf.index)) + " rows made")

                return resdf
            
            else:
                newdf = df.copy()
                for j in range(0,len(arr[index].queries)):
                    newcomb = combination.copy()
                    queryfulldata = {}
                    queryfulldata[arr[index].feature_name] = arr[index].queries[j]
                    queryfulldata = json.dumps(queryfulldata)
                    
                    newcomb.append(queryfulldata)
                    newdf = newdf.append(recursive_loop(arr,df,index+1,newcomb,colnames,ab_data,year),ignore_index=True)
                return newdf
        
        if len(query_steps) == 1:
            base_cohort = get_base_cohort(year)
            requests.packages.urllib3.disable_warnings()
            headers = {"Content-Type":"application/json", "accept":"application/json"}
            icees_url = 'https://icees.renci.org:16340/patient/' + str(year) + '/cohort/' + base_cohort + '/features'
            responsepkt = requests.get(icees_url,headers=headers, verify=False)
            if responsepkt.status_code != 200:
                print("Request failed {0}\n{1}\n{2}\n{3}".format(responsepkt.status_code, responsepkt.reason, responsepkt.request, responsepkt.text))
                sys.exit(-1)

            a_name = query_steps[0].feature_name
            selected = None
            selected_name = ""
            res = responsepkt.json()
            for i in res["return value"]:
                if i["feature"]["feature_name"] == a_name:
                    selected = i
                    selected_name = i["feature"]["feature_name"]
                    df = pd.DataFrame(index=np.arange(len(i["feature_matrix"])), columns=[selected_name,"frequency"])

            for j, row in df.iterrows():
                df.at[j, selected_name] = get_enum_name(selected_name, selected["feature"]["feature_qualifiers"][j]["operator"], extract(selected["feature"]["feature_qualifiers"][j]))
                df.at[j,"frequency"] = selected["feature_matrix"][j]["frequency"]

            df["cohort_name"] = 1
            df["cohort_bound"] = df["frequency"].sum()

            if write_to_csv:
                df.to_csv(write_to_csv,index=False)
            self.data = df

        elif len(query_steps) == 2:
            ab = {}
            ab["feature_a"] = query_steps[1].step_data
            ab["feature_b"] = query_steps[0].step_data
            ab = json.dumps(ab)
            base_cohort = get_base_cohort(year)
            df = generate_nvariate_table(base_cohort, ab, [query_steps[0].feature_name, query_steps[1].feature_name], [], year)

            df["cohort_name"] = 1
            df["cohort_bound"] = df["frequency"].sum()

            if write_to_csv:
                df.to_csv(write_to_csv,index=False)
            self.data = df

        else:
            colfull = []
            for i in range(0,len(query_steps)):
                colfull.append(query_steps[i].feature_name)

            colfull.extend(["frequency","cohort_name","cohort_bound"])

            #colreduced only has feature names
            colreduced = colfull[:-3]
            
            df = pd.DataFrame(columns=colfull)

            #writing columns
            if write_to_csv != None:
                df.to_csv(write_to_csv,index=False)
            
            ab = {}
            ab["feature_a"] = query_steps[-1:][0].step_data
            ab["feature_b"] = query_steps[-2:-1][0].step_data
            ab = json.dumps(ab)
            if print_debug:
                print("AB")
                print(ab)
            arr = query_steps[:-2]
            self.data = recursive_loop(arr,df,0,[],colreduced,ab_data=ab,year=year)

        print("QueryFull initialized.")
    
    
    def get_query_string(self) -> str:
        """String of feature names summarizing the query for user"""
        s = ""
        if len(self.steps) == 0:
            return "empty"
        for i in range(0,len(self.steps)):
            s += str(self.steps[i].get_step_string()) + "->"
        return s[:-2]
        
    def get_size(self) -> float:
        freq = self.data["frequency"].fillna(0)
        return freq.sum()

    def get_maximum_size(self) -> float:
        #not efficient but the best it can be working with csvs
        size = 0
        seen_cohorts = []
        for index,row in self.data.iterrows():
            if row["cohort_name"] in seen_cohorts:
                pass
            else:
                size += row["cohort_bound"]
                seen_cohorts.append(row["cohort_name"])
        return size

    def get_maximum_loss(self) -> float:
        return 1 - (self.get_size() / self.get_maximum_size())

class QueryAdditive:
    def __init__(self):
        self.query_data = []
        self.steps = [] #array of QuerySteps
        self.data = pd.DataFrame(index=[0],columns=["frequency"])
        self.cohort_size = 1
        self.empty = True
        
    def add_step(self,new_step):
        #TODO
        self.empty = False
        #update data with new contingency feature
        num_steps = len(self.steps)
        #going to univariate
        if num_steps == 0:
            pass
        #going to bivariate
        elif num_steps == 1:
            pass
        #going to nvariate
        else:
            new_step_len = len(new_step.feature_enum)
            #new_cols = self.data.columns
            #new_cols.insert(len(new_cols)-2,)
            #new_data = pd.DataFrame(index=np.arange(len(self.data)*new_step_len), columns=new_cols)
        
        #self.cohort_size = 
        self.steps.append(new_step)
        
    def get_query_string(self) -> str:
        """String of feature names summarizing the query for user"""
        s = ""
        if len(self.steps) == 0:
            return "empty"
        for i in range(0,len(self.steps)):
            s += str(self.steps[i].feature_name) + "->"
        return s[:-2]
        
    def get_data_loss(self) -> float:
        """Gives data loss between 0 and 1"""
        
        return 1 - (self.data["frequency"].sum() / self.cohort_size)

**Comment by karafecho** [comment]
To be replaced with several more concise issues.
