### ISSUE TITLE
Explanatory Agent error

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/icees-api#79]
From Rosina W.:

When running queries via Swagger we have been able to get results, but when we ran them from our agent's code, we are getting a time out. Any suggestions? This is the error we are getting.
SSLError: HTTPSConnectionPool(host='icees.renci.org', port=16340): Max retries exceeded with url: /query?reasoner=false (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

Kara's reply:

Hi Rosina. So, this error appears to be related to the restriction we've imposed on the number of service requests per second (I believe it is set at <=10). Just so you are aware, this restriction was required by our clinical data oversight committee. I may be mistaken, however, as the SSL suggests an encryption issue, but I suspect it's the requests per second. I'll post a ticket, just in case.

**Comment by patrickkwang** [comment]
We updated the SSL certificates, and I believe this should be fixed.

**Comment by karafecho** [comment]
Great! Thanks, Patrick.
