### ISSUE TITLE
Query issues/error messages from analytics team 

### ISSUE THREAD

**Issue by Sharma05** [NCATS-Tangerine/icees-api#84]
#### **Priya** 
**Query 1:** I tried again querying for Active_In_Year, TotalEDInpatientVisits, Sex, Race, Prednisone, ObesityDx, MaxDailyPM2.5Exposure_StudyMax, RoadwayDistanceExposure2, EstResidentialDensity in the order below:
query_steps = [QueryStep(stepsjson[0]),QueryStep(stepsjson[1]), QueryStep(stepsjson[2]), QueryStep(stepsjson[4]),
              QueryStep(stepsjson[5]),QueryStep(stepsjson[7]),QueryStep(stepsjson[8]),QueryStep(stepsjson[9])]
The frequency column is blank. 
When I generate Total_ed_visit, active in year with obesity and prednisone (only this 4) - I get an error as "Problem when generating bivariate table"
**Query 2** with: Active_In_Year, TotalEDInpatientVisits, Sex, Race worked fine
**Query 3** with: Active_In_Year, TotalEDInpatientVisits, MaxDailyPM2.5Exposure_StudyMax_qcut worked fine
**Query 4** with: Active_In_Year, TotalEDInpatientVisits, MaxDailyPM2.5Exposure_StudyMax_qcut, RoadwayDistanceExposure2 - worked fine

### **BO**
Below are the options that have issues:
**Issue 1:** I began querying with Active_In_Year, TotalEDInpatientVisits, and one predictor. 
1.      There is no problem when querying one of the following variables with the foresaid two variables.
Sex2     Race     MaxDailyPM2.5Exposure_StudyMax      RoadwayDistanceExposure2      EstResidentialDensity
query_steps = [QueryStep(stepsjson[0]),QueryStep(stepsjson[1]),QueryStep(stepsjson[2])]
query_steps = [QueryStep(stepsjson[0]),QueryStep(stepsjson[1]),QueryStep(stepsjson[3])]
…
2.       No data can be generated when “Prednisone” or “ObesityDx” is the predictor.
query_steps = [QueryStep(stepsjson[0]),QueryStep(stepsjson[1]), QueryStep(stepsjson[4])
query_steps = [QueryStep(stepsjson[0]),QueryStep(stepsjson[1]), QueryStep(stepsjson[5])
   
There was a Permission Error, shown below.
Initializing QueryFull with 3 features
Expected # of rows to generate: 22
---------------------------------------------------------------------------
PermissionError                          Traceback (most recent call last)
<ipython-input-7-3685127061a0> in <module>
     3                 ]  
     4
----> 5 x = QueryFull(query_steps,write_to_csv=CSV_NAME)
D:\BL\Renci\icees-kp-analytics\Python-BL\Query2010.py in __init__(self, query_steps, make_unknowns_zero, write_to_csv, print_help, print_debug, year)
   386            #writing columns
   387            if write_to_csv != None:
--> 388                df.to_csv(write_to_csv,index=False)
   389
   390            ab = {}
~\anaconda3\lib\site-packages\pandas\core\generic.py in to_csv(self,
path_or_buf, sep, na_rep, float_format, columns, header, index,
index_label, mode, encoding, compression, quoting, quotechar,
line_terminator, chunksize, date_format, doublequote, escapechar,
decimal)
  3202            decimal=decimal,
  3203        )
-> 3204        formatter.save()
  3205
  3206        if path_or_buf is None:
~\anaconda3\lib\site-packages\pandas\io\formats\csvs.py in save(self)
   186                self.mode,
   187                encoding=self.encoding,
--> 188                compression=dict(self.compression_args, method=self.compression),
   189            )
   190            close = True
~\anaconda3\lib\site-packages\pandas\io\common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text)
   426        if encoding:
   427            # Encoding
--> 428            f = open(path_or_buf, mode, encoding=encoding, newline="")
   429        elif is_text:
   430            # No explicit encoding
PermissionError: [Errno 13] Permission denied: 'data/yr2010_014.csv'
  
3.      "MaxDailyPM2.5Exposure_StudyMax" is very unbalanced data. 
Below is the data where frequency is greater than 0. As you can see, there are only 3 rows having category 5, the total frequency for category 5 is just 5, and the rest all belong to category 1.  However, the distribution is quite different from those in the previous final 9-feature data. Please see the bottom for the comparison.
   
 
**Issue 2:**  Data can be generated when querying the following 7 features. However, the total frequency is less than that of the previous 9-feature data. 
Active_In_Year  TotalEDInpatientVisits  Sex2     Race     MaxDailyPM2.5Exposure_StudyMax               RoadwayDistanceExposure2      EstResidentialDensity
 
 
  
**Issue 3:** No data can be generated when querying features with “Prednisone” or
“ObesityDx”. The one exception is querying the 9-features, which can
generate data with a timeout error. However, the frequency is blank.
Active_In_Year
  TotalEDInpatientVisits  Sex2     Race     Prednisone        ObesityDx
               MaxDailyPM2.5Exposure_StudyMax      RoadwayDistanceExposure2      EstResidentialDensity
 
![image (1)](https://user-images.githubusercontent.com/8516476/109677552-c7358500-7b47-11eb-8de6-a2a4cb8b6a8d.png)
![image](https://user-images.githubusercontent.com/8516476/109677554-c7358500-7b47-11eb-9e13-5ed4e0c8a7d7.png)

**Comment by karafecho** [comment]
To be replaced with several concise issues.
